### ISSUE TITLE
config.yaml reload

### ISSUE THREAD

**Issue by RedLeeder** [OliveTin/OliveTin#10]
**Is your feature request related to a problem? Please describe.**
First thing I did when creating a OliveTin instance was create an action to restart OliveTin so I could reload the config.yaml file with my updated actions.

**Describe the solution you'd like**
Best case would be 'Live Refresh' on a config.yaml file change.
2nd best would be a manual button that would reload the config.yaml file when clicked.

**Comment by jamesread** [comment]
Hey @RedLeeder , great suggestion, and actually something that the config library I'm using (Viper) already supports. I had to make some changes on the Javascript side of things, and the early functionality looks good.

I've got it so that shell commands and icons are easily changed and auto-reloaded, as well as adding actions. However, removing actions seems to have some problems. 

Even if it's a bit buggy at the moment, this will be included in the next release :-)

**Comment by jamesread** [comment]
This was included in version 2021-07-19

**Comment by jamesread** [comment]
@RedLeeder - I was thinking of closing this issue now - do you think the implementation matches what you had asked for? I like to try and get solid feedback on issues before closing them if at all possible. :-)

**Comment by RedLeeder** [comment]
I'll have to get the latest version and give it a whirl (to be honest I haven't checked it out recently) but if it lets me reload the config file without restarting OliveTin then that's exactly what I was looking for!
