### ISSUE TITLE
Dockerfile SSH

### ISSUE THREAD

**Issue by tamaskan** [OliveTin/OliveTin#12]
It should be mentioned that the SSH-Example("restart lightdm") is not possible with the default Dockerfile ("command not found")

**Comment by tamaskan** [comment]
dnf install openssh-clients solves that :-)

**Comment by jamesread** [comment]
Hey @tamaskan - thanks so much for taking the time to post the issue here. We managed to fix it for you in Discord a couple of days ago just by installing that extra package, but obviously others like you could have benefited from extra documentation.

Based on your comments, I've just updated the README in this repository, and the docs.olivetin.app site to add in this page; https://docs.olivetin.app/action-ssh.html

Do you think, with these extra notes and details, it would have fixed your original problem/question?

**Comment by tamaskan** [comment]
Sure, that's enough. I am now using it with a forced ssh-command and it works great. Thank you very much for your help
