### ISSUE TITLE
Install `docker` and `openssh-client` during image build.

### ISSUE THREAD

**Issue by Jafner** [OliveTin/OliveTin#13]
**Is your feature request related to a problem? Please describe.**
Attempting to run `docker` or `ssh`-based actions without installing these two fails.

**Describe the solution you'd like**
Add `dnf install -y docker && dnf install -y openssh-client` to Dockerfile.

**Describe alternatives you've considered**
Manually installing these services after the image has been deployed requires re-installation each time the container is created. In my use-case, where Docker Compose is used to statically define the container's configuration, adding a step after deployment is poor practice.

**Additional context**
I love OliveTin, and I hope I can contribute to its betterment.

**Comment by jamesread** [comment]
I gave this some re-thinking since it was mentioned in #12. 

Using docker and ssh is a very common use case for OliveTin, and because the docker images are provided as a convenience, it makes sense to make them as convenient as possible. 

Added in the latest updated container images that have now been published. 

Thanks for the comment. :-)
