### ISSUE TITLE
No way to specify docker host 

### ISSUE THREAD

**Issue by djeinstine** [OliveTin/OliveTin#142]
**What seems to be the problem?!**

Cannot specify docker host.

I'd like to be able to run docker commands using the containerised version of olivetin. However, it currently assumes the docker host lives at `unix:///var/run/docker.sock`. I would like to use a socket to protect my system. Therefore the socket is now at `http://socket_proxy:2357`.

Nowhere in the docs does it show how to change the host. Can someone please help me?

**Comment by jamesread** [comment]
Hey, OliveTin doesn't do anything special with the docker API, it simply is executing the docker command line like you would normally. 

Most people simply run OliveTin on the same host as docker, and pass through the docker sock to the OliveTin container. I don't see how this is insecure.

**Comment by djeinstine** [comment]
Accessing the socket using the Unix host directly is not secure. See: https://medium.com/@containeroo/traefik-2-0-paranoid-about-mounting-var-run-docker-sock-22da9cb3e78c

Using a socket proxy should be standard. I protect my system using a proxy. And I'm actually surprised the docker host is not an environmental variable one can change. Otherwise I'd have to redo my entire architecture just for olivetin because my Unix:// host is not accessable directly. Only via the socket proxy.

 Every other docker project has a variable `DOCKER_HOST` . 

Anyhow, is there a workaround? If I know the line of code I have to change I could just rebuild the image.

**Comment by jamesread** [comment]
Hey @djeinstine, I understand what you are saying, but I don't agree with the point about it being more secure. 

That is because this technique does not avoid mounting the docker socket, you're simply going through a proxy, which just adds another layer to the security onion. While I appreciate that the proxy acts as an "API Firewall", it also increases the attack surface - before, the docker sock was not exposed to the network, but now, with the proxy, it is! 

However, I don't think OliveTin stops you from doing this if that's what you'd like to do. 

OliveTin doens't have any docker-specific API code - OliveTin simply runs shell commands. For doing Docker actions, it is very simply using the Docker CLI just like you would, when you create an action in OliveTin. 

If the normal approach for specifying the location of the docker host is via and environment variable, and if the Docker CLI uses this environment variable, then simply do this in the OliveTin configuration;

````
actions:
  - title: Stop container
    shell: DOCKER_HOST=10.80.0.1:1028 docker stop mycontainer
````
