### ISSUE TITLE
user interaction with the script

### ISSUE THREAD

**Issue by fpirri** [OliveTin/OliveTin#22]
**Interaction with the bash script**
All is good with 'fire and forget' actions with no parameter. 
There are other very interesting scenarios which require some form of interaction. Can we use OliveTin in those cases?

My OliveTin is OliveTin_2021-07-19_linux_amd64.deb, running in ubuntu 20.04
My script is of the type 'sudo bashcommand', how do I send the user's password?
The action complete without errors but the log show nothing.
Can I find docs for this type of script?

More generally, how do I allow a script to accept user input and continue processing?
I have scripts which require input from user in the middle of processing: can I interact with the script in some way?

Thank you for your help

**Comment by ashleycawley** [comment]
I'm not a developer of OliveTin so I will leave it to James to decide but it feels to me that your requests are a little out of the scope of what OliveTin was designed for (I may be wrong). But if you're running the types of scripts that required back and forth interactions between the user, providing passwords, prompted user-input, OliveTin may not be the best tool for what you need.

You may be better off building your own web page using PHP or something similar which is custom to your requirements, or seeking someone who can do that for you.

We each have our own use-cases for OliveTin I'm sure and its not up to me what its scope will be to encompass in the future. So I'll hand that over to James.

To help you with:
> My script is of the type 'sudo bashcommand', how do I send the user's password?

If you have setup sudo rights for your user then you can tweak settings on your computer or server so that it doesn't ask you for the password when you sudo, [see here](https://askubuntu.com/questions/147241/execute-sudo-without-password).

**Comment by jamesread** [comment]
Hey @fpirri , thanks for your interest in OliveTin, and sorry that you couldn't figure out what you wanted to do - or if it was possible.

At the moment, I'm designing OliveTin to work with automated commands and scripts that don't require user input (the technical term for this, is a tty, or a shell). Any time your script asks for input (eg, doing a Python `raw_input`), it will get a EOF (end of file) character and just quit silently, normally. That's probably what you're experiencing here. 

However, there is a very good argument for being able to pass arguments to a script when it starts up, for example a password, or a user id, or whatever. This is something that I am working on, and exploring in Issue #6 . 

Could you share a bit more about your use case - could your script be adapted so that it asks for all it's input as arguments into the script? Have a read of #6 and see some of the early screenshots - would that solution work for you? 

Thanks again for your interest in the project, and thanks too to @ashleycawley for adding valuable comments - you and I are thinking the same :-)

**Comment by fpirri** [comment]
@ashleycawley , thanks for the comment above, I think I will follow it, at least in the most complicated cases.

**Comment by fpirri** [comment]
@jamesread , thank you for your suggestion. I will use the suggestion of @ashleycawley for a few script, then I can use the OliveTin latest version for some cases of mine.
Anyway, I think that what I see in Issue #6 can solve the problem for a number of use cases, so, thanks again for your work.

**Comment by ashleycawley** [comment]
No problem, glad to be of assistance. I'm guessing this one can be closed now then :-)
