### ISSUE TITLE
titlealias is not a valid key

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#232]
With the latest version 2024.02.27, it looks like `titlealias` is not recognized and olivetin is not even coming up. It was working without any issues until the previous version.

The titleAlias was used to call an action via the `api/StartAction`. So I assume the api call wouldnt work as well because of this.

```
- title: Restart HA
  titleAlias: homeassistant
  icon: "&#9851;"
  shell: docker restart homeassistant
  timeout: 100
```

**Logs**
```
Config unmarshal error 1 error(s) decoding: * 'actions[1]' has invalid keys: titlealias
```

**Comment by jamesread** [comment]
I'm sorry, I should have added this to the release notes. It changed to "id" now. 

I was updating the docs yesterday to reflect this, but I'll put a warning on that page. 

https://docs.olivetin.app/action-ids.html

I assume you were using titleAlias because of the API - note that some API calls got changed and standardized too: 

https://docs.olivetin.app/api-start-action.html

**Comment by accforgithubtest** [comment]
Yes, that was it. Changing it to id in the config and updating the api endpoint fixed it.
Thank you for the quick reply, cheers !
