### ISSUE TITLE
--config flag

### ISSUE THREAD

**Issue by ManuelFte** [OliveTin/OliveTin#38]
As per the [documentation on how to set up multiple instances](https://docs.olivetin.app/multi-inst.html), I'd like to suggest the addition of a feature that could make the process even simpler: a flag (tentatively called `config`, but the name is irrelevant) that allows to specify the location of the `config.yaml` when this is not in the default directory.

For example, in order to create a second OliveTin instance, all I'd have to do would be to place a second `config.yaml` in `/home/myuser/OliveTin2`, and then call the executable located in `/usr/local/bin/OliveTin` with this service file:

```
[Unit]
Description=OliveTin2

[Service]
ExecStart=/usr/local/bin/OliveTin --config /home/myuser/OliveTin2/config.yaml
Restart=always

[Install]
WantedBy=multi-user.target
```

This differs from the method in the documentation in that it doesn't need to use a different copy of the executable for each instance, as it can use one executable for all instances; including the one installed in the default location by the .deb/.rpm installer.

It'd also allow to give the `config.yaml` any name, which would make possible to have multiple configuration files in the same directory (for example, I could have `/home/myuser/OliveTin_configs` with files called `config2.yaml`, `config3.yaml`, etc.). 

And even though it's possible to do something similar simply by specifying a `WorkingDirectory` in the service file, this is a more cross-OS method. For example, if I was using Windows, I could make a shortcut that called the executable this way:

 `C:\Program Files\OliveTin\OliveTin.exe --config C:\Users\MyUser\OliveTin2\config.yaml`

Or it could be used for distros that don't use `systemd`, or if for some reason I can't or don't want to use a service file; for example, if I'm running it on a machine where I don't have root permissions (the latter could be paired with a `webUIDirectory` option in the `config.yaml` that similarly allows to choose a different location for the web files, but that's independent from this suggestion).

**Comment by jamesread** [comment]
Hey @ManuelFte , excellent suggestion. Actually when reading your comments back in the discord, and looking at the code, I thought to myself the same thing - having an argument for a custom config path makes a lot of sense. 

I'll set to work on this for a future version of OliveTin.

**Comment by ManuelFte** [comment]
@jamesread Thank you. I edited the suggestion after your reply, I think I've refined the idea a bit.

Originally I was suggesting a `--config.path` flag that points OliveTin to the _directory_  where to find the `config.yaml`, but then I thought that a flag called `--config` that points directly to the file would be more useful, as you could have multiple configuration files in the same directory, rather than having to make a different directory for each. I don't know if you still agree with this modified suggestion.

**Comment by jamesread** [comment]
This design will need a bit of extra thought - a switch to --config-file instead of --config-dir has implications; 

Currently OliveTin just looks in a couple of paths for a hardcoded filename of "config.yaml". This isn't very flexible, but it is the basis of having a config.d style method of loading several partial config files in a directory. Splitting out configuration may be useful for those people who have quite a few actions, so is an option I'd like to keep open for the future. 

I don't personally like the "include" style syntax used by some apps, as then the configuration becomes a type of code and people often end up doing odd things with that. 

I'll poke around with the design shortly.

**Comment by ManuelFte** [comment]
Ah, I see. Then how about making `--config` take multiple files in the same flag? So if my configuration file is split into pieces, I call them all like this:

`--config /path/config.yaml /path/config2.yaml ...`.

Or maybe `--config` could accept either a file or a directory. If supplied a directory, all YAML files in it are taken as the same config file split into pieces. If supplied a file, only that particular file is used as config.

Or instead of one flag there could be two, `--config-dir` and  `--config-file`, depending on the user's needs.

Whatever is simpler to code and for the user to understand. 🤔

**Comment by jamesread** [comment]
Hey @ManuelFte , thanks for taking the time again to write up this feature request - it's taken me a little while to look at it because I've been busy with other life stuff. 

I've decided to go for `--configDir`, because there are more things that will be written into the config directory in the future (like instance IDs, themes, etc). A configDir gives more options to expand in the future than something like `--configfile`. At the moment all configuration needs to be within a single file, but it would be great to have several config files in a directory supported in the future. 

The code for this is done, but before it makes it into the next release, I need to do;

- [ ] Documentation for `--configDir` on docs.olivetin.app
- [ ] Integration tests, using a different config directory (that will be fun!)

**Comment by jamesread** [comment]
This feature was released in https://github.com/OliveTin/OliveTin/releases/tag/2022-04-07

Thank you very much @ManuelFte for raising it!
