### ISSUE TITLE
Pass current authenticated username as an argument/variable.

### ISSUE THREAD

**Issue by Maokaman1** [OliveTin/OliveTin#405]
Hey @jamesread,

I'm about to deploy your excellent product, and after reviewing the documentation, I couldn't find a way to pass the current authenticated username as an argument to a command/script. This functionality could be useful in scenarios such as notifying others in chat groups or initiating approval processes before executing dangerous scripts.

Additionally, it might be worth considering whether built-in usernames (e.g., cron, calendar, fileindir) should be prefixed to reduce the risk of conflicts with usernames in external authorization systems. I'm not entirely sure about this, but it could be something to think about.

**Comment by jamesread** [comment]
Hey @Maokaman1 , that's a very sensible request. I've just written code for it and submitted it in #406. I'll publish a release that includes this in just a moment. :-) 

All OliveTin fake users are members of the "system" usergroup, which should make it easy to filter permissions, I don't really want to rename them like ot_calendar because a conflict is fairly unlikely.
