### ISSUE TITLE
Changing webroot

### ISSUE THREAD

**Issue by 33masterman33** [OliveTin/OliveTin#53]
Is there anyway that I would be able to change the style of the url from for example 192.168.0.x:1337 to 192.168.0.x:1337/OliveTin? I looked around in all the different files but couldn't figure out how to do it. I am trying to put it behind a reverse proxy under a location instead of subdomain. I do this to organize all my services without needing a bunch of subdomains

**Comment by 33masterman33** [comment]
Wow talk about good timing. I've really enjoyed the ease of running bash scripts though this project so this will just make it even better. I'm using nginx proxy manager v2.9.16. Which is pretty much just nginx in docker.

**Comment by jamesread** [comment]
Hey @33masterman33 , if you could give the recent https://github.com/OliveTin/OliveTin/releases/tag/2022-04-07 release ago, that would be awesome. The Javascript client code now uses a relative link (`./api/` instead of (`/api/` for the root), which should mean that custom "web roots" just work - eg: "http://localhost:80/OliveTin/" or "http://example.com/dashboard", or whatever.

If that doesn't work for you, then could you post a screenshot and/or browser console log so we can work out what's going on?

To override it, you can now also set `ExternalRestAddress: http://example.com/` in your config.yaml (I still need to document this). This was only added in the 2022-04-07 release.

**Comment by 33masterman33** [comment]
@jamesread I followed the documentation and it works perfectly after I figured out I forgot the semicolon after http in the externalRestAddress
