### ISSUE TITLE
perhaps a better way to install using docker?

### ISSUE THREAD

**Issue by aristosv** [OliveTin/OliveTin#60]
**Is your feature request related to a problem? Please describe.**
No, this is not a problem, it's just a personal preference to make container installation simpler

**Describe the solution you'd like**
I’m in no way a docker expert so don’t get me wrong if I say something incorrectly. I’ve been using linuxserver.io images for some time now and I like how they are logically built and consistent. 

When using linuxserver.io containers:

- There is no need to create any additional directories on your docker server
- No need to create configuration files, as they are included in your volume after installation
- The volumes are always persistent 
- The volumes are always located under /var/lib/docker/volumes/$containername/_data.
- The container always starts automatically when the installation finishes.
- No need to define -v /explicit/path. You can use -v containername:/config

So today I tried installing OliveTin using this command, instead of following the official documentation, just to see if it would work.

```
#!/bin/bash

docker pull docker.io/jamesread/olivetin
docker run -d \
 --restart=always \
 --name olivetin \
 -h olivetin \
 -e PUID=1001 \
 -e PGID=1001 \
 -e TZ=Europe/Nicosia \
 --net=network \
 -p 1337:1337 \
 -v olivetin:/config:ro \
 docker.io/jamesread/olivetin
```

After the installation finished successfully I noticed that the olivetin container didn't have an IP or a port defined in portainer. Which would make sense I guess because I didn't follow the official documentation for docker installation.

![Greenshot 2022-05-07 17 18 27](https://user-images.githubusercontent.com/528302/167258431-2a5a0758-4d3b-455d-9309-0cc3a4edd96b.png)

All I'm saying here is that there might be a better, simpler way to install olivetin using docker without the need to create directories, configuration files, manually start the container, or use explicit paths. Just a single command, and it's up and running.

Again, I'm no docker expert and I might be completely wrong.

**Comment by jamesread** [comment]
Hey @aristosv , first of all, thanks for taking the time to write this up here - I've been on holiday for the last few days and am just having time to check back on GitHub issues now. 

So, the general point that you raise about making OliveTin easy to setup & use is certainly something I'm interested in - anything to make it better I'd consider.

The PUID and PGID variables are actually hacks from the lsio project, from before Docker had support for running containers as different users. This is captured in the OliveTin documentation here; https://docs.olivetin.app/no-puid-pgid.html . However, I think it would be good to additionally warn users in OliveTin that PUID and PGID are ignored - I've created a separate issue for this; https://github.com/OliveTin/OliveTin/issues/62 

> There is no need to create any additional directories on your docker server
> The volumes are always persistent
> The volumes are always located under /var/lib/docker/volumes/$containername/_data.
> No need to define -v /explicit/path. You can use -v containername:/config

So, I need to better understand how docker handles "volumes" - as I am just used to bind mounting directories. I'll track that in this ticket and come back with some feedback. The screenshot you shared - what web interface is that - proxmox, or something?

> No need to create configuration files, as they are included in your volume after installation

Yep, this is something that OliveTin absolutely could do better - it should generate a default configuration file. I've created issue https://github.com/OliveTin/OliveTin/issues/63 to track this. There are some downsides to implementing this though, so I've started describing those issues in #63 . 

> The container always starts automatically when the installation finishes.

This could just be due to how you're starting / creating containers - using `create` (as in the documentation) instead of `run`. 


Thanks for your time in describing your experience, and suggesting improvements. I hope I've taken everything on-board, and will look at these individual issues over the next few weeks.

**Comment by jamesread** [comment]
@aristosv , thanks very much for raising this issue some time ago, it's a shame that I have not been able to provide an update until now! 

#62, #63 and others were resolves some time ago, meaning that all these issues are essentially fixed; 

    There is no need to create any additional directories on your docker server
    No need to create configuration files, as they are included in your volume after installation
    The volumes are always persistent
    The volumes are always located under /var/lib/docker/volumes/$containername/_data.
    The container always starts automatically when the installation finishes.
    No need to define -v /explicit/path. You can use -v containername:/config

Thanks taking the time to provide feedback and make OliveTin better :-) If you feel you have more suggestions, or I didn't address your suggestions, please do re-open this issue and comment, or create a new issue. I'm always willing to listen to feedback!
