### ISSUE TITLE
Standard naming convention for releases

### ISSUE THREAD

**Issue by Hudater** [OliveTin/OliveTin#68]
**Is your feature request related to a problem? Please describe.**
Don't include version name in releases. Tag based release identifiers make it easy to curl latest package in a script

**Describe the solution you'd like**
Rather than release named `OliveTin_2022-04-07_linux_amd64.deb`, it should be `OliveTin_linux_amd64.deb`

**Additional context**
Follow a standard naming convention for release names since tags serve as release number.
For practical representation, refer to [Adguard Home's release page](https://github.com/AdguardTeam/AdGuardHome/releases)

**Comment by jamesread** [comment]
Hey @Hudater. OliveTin does actually use a standard for naming - it uses "Calendar Versioning" - http://calver.org . I guess this is different to what most people use - Semantic Versioning ( http://semver.org ). 

I don't like the idea of removing the version from package names, because some folks want to install a specific version. 

However, maybe your problem could be worked around by having a "-latest" package as well. GitHub sadly doesn't make it easy to "symlink" a "latest" version to a real version, so I would need to think about how to do that.

Could you tell me a bit more about the script you are using - why are you writing it, and why is specifying the version number (instead of "latest") difficult?

**Comment by Hudater** [comment]
Hello there James, Thanks for letting me know about versioning standards since I didn't know those existed.

For users who want to use a specific version number, there is already version tag in download URL just after `/releases/download/`
(https://github.com/OliveTin/OliveTin/releases/download/2022-04-07/OliveTin_2022-04-07_linux_amd64.deb)

Arguably, it's better for them too to have Semantic Versioning so that they have to change only one part of the URL for the specific version they want.
For example, for version `2022-04-07` rather than using this URL (https://github.com/OliveTin/OliveTin/releases/download/2022-04-07/OliveTin_2022-04-07_linux_amd64.deb) they can use (https://github.com/OliveTin/OliveTin/releases/download/2022-04-07/OliveTin_linux_amd64.deb)

About the script, I wanted to create a simple installer for OliveTin in form of a bash script. I have one for [adgaurd-home](https://github.com/Hudater/services/blob/main/baremetal/adguard/installation.sh) if you want to look. It just makes it easy to re-configure my homelab.

If I specify version name, I would have to constantly update the script to be at the latest version.

**Comment by jamesread** [comment]
Hey there, I was really not sure if I wanted to do this or not, so spent a bit of time thinking about it.

What I thought was that it would be useful to know which version of OliveTin you're looking at when looking at an install file (.zip, .rpm, etc). However, there are other ways of doing this.

Downloading a OliveTin.rpm will overwrite any local older version - which is probably good as most people don't want to keep old versions of the software around. 

So, yep, I've made this change in commit [9df1a12](https://github.com/OliveTin/OliveTin/commit/9df1a127c2992fa72c28c585eef9a59363c9b6d6) which should be OK. I'm just waiting for the build to complete before marking this issue as done.

**Comment by Hudater** [comment]
Thanks a lot for your time and the changes :)

**Comment by jamesread** [comment]
This change is now live with the latest release, thanks @Hudater !
