### ISSUE TITLE
Add `docker compose` to docker images by default

### ISSUE THREAD

**Issue by Crydsch** [OliveTin/OliveTin#89]
I really appreciate that `docker` is pre-installed in the images.
It would be even better, if the `docker compose` plugin was installed as well.

This would allow simple compose based services to be restarted etc..
i.e. `shell: docker compose up -d`

Based on [the official docker docs](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually) this works:

```bash
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
 -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
```

This could be added to the `RUN` "install"command in the Dockerfiles.

**Comment by jamesread** [comment]
Hey @Crydsch , sorry that you've been waiting a little while for a reply here - the run up to Christmas etc has been busy!

I understand that docker-compose is useful for you, but I'd need to see more demand from other users before considering to add it to the base OliveTin image - there are 3 considerations generally when adding new packages; 

1) Does this increase the size of the base image much (in this case, no, docker-compose is just 250kb
2) Can this package easily be installed using dnf? (in this case, yes, `dnf install docker-compose`), https://docs.olivetin.app/container-dnf.html
3) Would enough people use this? (see below)
4) Does it make the builds take a lot longer? (this is a huge problem especially for ARM-based container images - would need to test this)

So, I need more info on "3) Would enough people use this?" - if you're reading this post and thinking you'd like docker-compose included by default, please :+1: the first post so that I can see how many people are asking for this. If we go past 5 or 10 people, then I can think about adding it. Thanks!

**Comment by flammable** [comment]
Hi! I just started using OliveTin, and I really like it. Thanks for this!

Running `docker compose` within OliveTin is an issue I'm encountering, too. Per the documentation, I'm running OliveTin as root, so I run this to be able to run commands within the container:

`docker exec -it olivetin /bin/bash`

I'm not sure why, but `docker exec -it olivetin -u root /bin/bash` fails with this error:

> OCI runtime exec failed: exec failed: unable to start container process: exec: "-u": executable file not found in $PATH: unknown

From there, I get "command not found" when running `dnf`, but I am able to get `microdnf` working (I see the Dockerfile is using this, too).

That said, it looks like running `microdnf install docker-compose` attempts to download and install `docker-compose` version 1.29.2-4, which is an old version. Some people might prefer that, but I think @Crydsch pasted the instructions for the newer `docker compose` (note the missing `-`) which is not based on Python.

It looks like [it's possible to install this on Fedora](https://docs.docker.com/engine/install/fedora/#set-up-the-repository) using `dnf`, but I'm not sure if that'd be faster than the manual steps included above.

**Comment by flammable** [comment]
Update: either of these seem to work:

```
/usr/bin/docker exec -i olivetin /bin/bash -c "/bin/microdnf install -y yum-utils && /bin/dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && /bin/dnf install -y docker-compose-plugin"
/usr/bin/docker exec -i olivetin /bin/bash -c "/bin/mkdir -p /usr/local/lib/docker/cli-plugins && /bin/curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && /bin/chmod +x /usr/local/lib/docker/cli-plugins/docker-compose"
```

The second one is significantly faster, though. Since it's installing less, I'm guessing it's also requiring less disk space.

**Comment by jamesread** [comment]
Hey @flammable , this looks nice - combining your comments with @Crydsch, this would make for good documentation in the meantime. 

It looks like the latest version of Fedora still packages this "older" docker-compose; https://src.fedoraproject.org/rpms/docker-compose

**Comment by flammable** [comment]
Thanks! Here's what I put together last night, so I don't need to install interactively.

```
#!/bin/bash

docker="/usr/bin/docker"
echo="/usr/bin/echo"
grep="/usr/bin/grep"

# Install Docker Compose in olivetin
container_name="olivetin"
if ${docker} ps --format '{{.Names}}' | ${grep} -Eq "^${container_name}\$"; then
  # ${docker} exec -i "${container_name}" /bin/bash -c "/bin/microdnf install -y yum-utils && /bin/dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && /bin/dnf install -y docker-compose-plugin"
  ${docker} exec -i "${container_name}" /bin/bash -c "/bin/mkdir -p /usr/local/lib/docker/cli-plugins && /bin/curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && /bin/chmod +x /usr/local/lib/docker/cli-plugins/docker-compose"
else
  ${echo} "${container_name}" not running
fi

exit
```

I think I see how to edit the documentation. I'll submit a PR!
